const googleRouter = require("./authGoogle");
const authRouter = require("./auth");
const userRouter = require("./user");
const productRouter = require("./admin/product/product");
const userRoutes = require("./admin/auth/userRoutes");
const brandRouter = require("./admin/brands/brands");
const vnpayRouter = require("./admin/vnpay/order");
const WathListRouter = require("./product/product");
const CartRouter = require("./product/cart");
const supplierRoutes = require("./admin/suppliers/suppliers");
const adminProduct = require("./admin/product_v2");
const clientProduct = require("./client/product");
// const productRouter_v2 = require("./admin/product_v2");
const inboundRouter = require("./admin/inboundshipments/inbound");
const inventoryRouter = require("./admin/inventory");
// const supplierRoutes = require("./admin/suppliers/suppliers");
const auctionRouter = require("./admin/auctions/randBid.routes");
const routes = (app) => {
  app.use("/api/auth", authRouter);
  app.use("/api/auth", googleRouter);
  app.use("/api/user", userRouter);
  app.use("/api/product", productRouter);
  app.use("/api/admin", userRoutes);
  app.use("/api/suppliers", supplierRoutes);
  // app.use("/api/product_v2", productRouter_v2);
  app.use("/api/vnpay", vnpayRouter);
  app.use("/api/cart", CartRouter);
  app.use("/api/brands", brandRouter);
  app.use("/api/suppliers", supplierRoutes);
  app.use("/api/admin/product", adminProduct);
  app.use("/api/client/product", clientProduct);
  app.use("/api/brands", brandRouter);
  // app.use("/api/suppliers", supplierRoutes);
  app.use("/api/wathlist", WathListRouter);
  app.use("/api/auctions", auctionRouter);
  app.use("/api/inbound", inboundRouter);
  app.use("/api/inventory", inventoryRouter);

};

module.exports = routes;
